### ISSUE TITLE
Комментарий от ментора

### ISSUE THREAD

**Issue by mdwebppua** [iliapavlov/iliapavlov.github.io#1]
**Визуально** - хорошо, добавить тень.

**Размещение файлов** - все хорошо"

**Разметка html кода файла index.html:** 
_Очень много лишних `<div>`_  - лучше использовать тег `<p>` для текста
картинка, сделано правильно, но лучше сделать так
нужно было задать в отдельный блок например:
 `<div class="fotoUser"><img src="images/profile-photo.jpg" alt="наш студент"></div>`

**Файл стилей css:**
не указан размер шрифта, указать всему документу!
`.rez` -  не нужно было задавать параметр height: 750px; (убрать) так как если текста будет больше, документ не потянется или задать параметр min-height, но зачем лишний скрол.
если Вы измерили ширину документа она у вас получилась 510px, нужно задать внутренний отступ padding: 30px 50px; и нужно отнять padding от ширины.
margin-left: 462px; не правильно исправить, нужно задать одним параметром margin: 0 auto;
`.blo` - padding-left: 60px; убрать так как нужно задать всему документу, как я написал выше.
`<hr align="center" width="410">` - сделать просто `<hr>` без стилей
`ul` - задать правильно отступы одним padding

Перенос строк использовать `<br/>`

После исправления написать в чат,  перепроверю!

**Comment by mdwebppua** [comment]
Структура папок не верная!

**Comment by mdwebppua** [comment]
блок `<p class="one-line"></p>` не должен быть пустым! Это тоже самое что и `<hr>` исправить!

**Comment by iliapavlov** [comment]
Исправил. Добавил дивы, которые рисуют линию.

**Comment by mdwebppua** [comment]
**ЗАЧЕТ**
